### ISSUE TITLE
Checklist for Gitbook open-source application

### ISSUE THREAD

**Issue by kalouo** [kalouo/breadcrumbs#1]
- [x] Exists on GitHub or GitLab
- [x] Is not just an empty repository with nothing to show
- [x] Is not just a fork with no activity of its own
- [x] Has a README.md file that clearly explains what the software is about
- [ ] Has a CONTRIBUTING.md file that explains how to contribute
- [x] Has a LICENSE file with [a valid OSS license](https://choosealicense.com/)
- [x] Has a CODE_OF_CONDUCT.md
- [x] Has a pull request template
- [x] Has an issue template 
- [x] CICD linting
- [x] CICD tests
- [x] CICD dependency checks
